---
title: "openmindR"
output: github_document
---

Install package like this:

```{r setup, eval=FALSE}
devtools::install_github("favstats/openmindR")
```

Load package:

```{r}
library(openmindR)
```


## Openmind ggplot2 theme

There are three functions for the ggplot2 theme:

+ `theme_om`
+ `scale_fill_om`
+ `scale_color_om`

Make sure you have the Poppins font installed!

```{r}
windowsFonts(`Poppins` = windowsFont("Poppins"))

```


[Good tutorial on how to install custom fonts in R](https://www.andrewheiss.com/blog/2017/09/27/working-with-r-cairo-graphics-custom-fonts-and-ggplot/)

**Example**

```{r fig.width=8, fig.height=5, message=F, warning=F}
## Load tidyverse
library(tidyverse)

titanic_dat <- Titanic %>% as_tibble()

titanic_dat %>% 
  ggplot(aes(Sex, n)) +
  geom_col(aes(fill = Class), position = position_dodge()) +
  theme_om(legend_position = c(0.9, 0.75)) +
  scale_fill_om("Class") +
  facet_wrap(~Survived) +
  labs(title = "Titanic Survival by Age and Class") 
  
```

**Adapt `theme_om`**

+ `legend_position`
+ `axis_text_size`
+ `axis_title_size`
+ `legend_text_size`
+ `title_size`

```{r fig.width=8, fig.height=5, message=F}
titanic_dat %>% 
  ggplot(aes(Class, n, fill = Class)) +
  geom_col() +
  theme_om(legend_position = "bottom",
           axis_text_size = 10,
           axis_title_size = 15, 
           legend_text_size = 10,
           title_size = 20) +
  scale_fill_om() +
  facet_wrap(~Survived) +
  labs(title = "Titanic Survival by Class") 
```

Or all text sizes at once

+ `overall_text_size`

```{r fig.width=8, fig.height=5, message=F}
titanic_dat %>% 
  ggplot(aes(Class, n, fill = Class)) +
  geom_col() +
  theme_om(legend_position = "top",
           overall_text_size = 15) +
  scale_fill_om() +
  facet_wrap(~Survived) +
  labs(title = "Titanic Survival by Class") 
```

